const wordActionTypes ={
    CREATE_WORD_START : 'CREATE_WORD_START',
    CREATE_WORD_SUCCESS:'CREATE_WORD_SUCCESS',
    CREATE_WORD_FAILURE:'CREATE_WORD_FAILURE',
    DELETE_WORD_START : 'DELETE_WORD_START',
    DELETE_WORD_SUCCESS:'DELETE_WORD_SUCCESS',
    DELETE_WORD_FAILURE:'DELETE_WORD_FAILURE',
    FETCH_WORD_START:'FETCH_WORD_START',
    FETCH_WORD_START_FROM_USER:'FETCH_WORD_START_FROM_USER',
    FETCH_WORD_SUCCESS:'FETCH_WORD_SUCCESS',
    FETCH_WORD_FAILURE:'FETCH_WORD_FAILURE',
    UPDATE_WORD_LIMIT:'UPDATE_WORD_LIMIT'

}

export default wordActionTypes;