const wordActionTypes ={
    CREATE_WORD_START : 'CREATE_WORD_START',
    CREATE_WORD_SUCCESS:'CREATE_WORD_SUCCESS',
    CREATE_WORD_FAILURE:'CREATE_WORD_FAILURE',
    DELETE_WORD_START : 'DELETE_WORD_START',
    DELETE_WORD_SUCCESS:'DELETE_WORD_SUCCESS',
    DELETE_WORD_FAILURE:'DELETE_WORD_FAILURE',
    FETCH_WORD_START_FROM_USER:'FETCH_WORD_START_FROM_USER',
    FETCH_WORD_SUCCESS:'FETCH_WORD_SUCCESS',
    FETCH_WORD_FAILURE:'FETCH_WORD_FAILURE',
    UPDATE_WORD_LIMIT:'UPDATE_WORD_LIMIT',
    SEARCH_WORD_START : 'SEARCH_WORD_START',
    SEARCH_WORD_SUCCESS:'SEARCH_WORD_SUCCESS',
    SEARCH_WORD_FAILURE:'SEARCH_WORD_FAILURE',

}

export default wordActionTypes;